spring:
  cloud:
    azure:
      msi-enabled: true
      client-id: [the-id-of-managed-identity]
      resource-group: [resource-group]
      subscription-id: [subscription-id]

#     Uncomment below configurations if you want to enable auto creating resources.
#      auto-create-resources: true
#      region: [region]

    stream:
      bindings:
        consume1-in-0:
          destination: [servicebus-queue-1-name]
        supply1-out-0:
          destination: [servicebus-queue-1-name-same-as-above]
        consume2-in-0:
          binder: servicebus-2
          destination: [servicebus-queue-2-name]
        supply2-out-0:
          binder: servicebus-2
          destination: [servicebus-queue-2-name-same-as-above]

      binders:
        servicebus-1:
          type: servicebus-queue
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    namespace: [first-servicebus-namespace]
        servicebus-2:
          type: servicebus-queue
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    namespace: [second-servicebus-namespace]
      servicebus:
        queue:
          bindings:
            consume1-in-0:
              consumer:
                checkpoint-mode: MANUAL
            consume2-in-0:
              consumer:
                checkpoint-mode: MANUAL
      function:
        definition: consume1;supply1;consume2;supply2;
      poller:
        initial-delay: 0
        fixed-delay: 1000
