spring:
  cloud:
    azure:
      msi-enabled: true
      client-id: [the-id-of-managed-identity]
      resource-group: [resource-group]
      subscription-id: [subscription-id]

#     Uncomment below configurations if you want to enable auto creating resources.
#
#      auto-create-resources: true
#      environment: Azure
#      region: [region]

      servicebus:
        namespace: [servicebus-namespace]
    stream:
      bindings:
        input:
          destination: [servicebus-queue-name]
        output:
          destination: [servicebus-queue-name-same-as-above]
      servicebus:
        topic:
          bindings:
            input:
              consumer:
                checkpoint-mode: MANUAL