spring:
  cloud:
    azure:
      client-id: [service-principal-id]
      client-secret: [service-principal-secret]
      tenant-id: [tenant-id]
      resource-group: [resource-group]

#     Uncomment below configurations if you want to enable auto creating resources.
#
#      subscription-id: [subscription-id]
#      auto-create-resources: true
#      environment: Azure
#      region: [region]

      servicebus:
        namespace: [servicebus-namespace]
    stream:
      bindings:
        consume-in-0:
          destination: [servicebus-topic-name]
          group: [topic-subscription-name]
        supply-out-0:
          destination: [servicebus-topic-name-same-as-above]
      servicebus:
        topic:
          bindings:
            consume-in-0:
              consumer:
                checkpoint-mode: MANUAL
      function:
        definition: consume;supply;
      poller:
        fixed-delay: 1000
        initial-delay: 0
