language: java
sudo: false
jdk:
- oraclejdk7
- oraclejdk8
- openjdk7
script:
- |-
  if [ ${TRAVIS_EVENT_TYPE} = "push" -o ${TRAVIS_EVENT_TYPE} = "pull_request" ]; then
   mvn install -DskipTests=true || travis_terminate 1 ;
   mvn test -Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dsurefire.rerunFailingTestsCount=6|| travis_terminate 1 ;
   mvn checkstyle:check || travis_terminate 1 ;
   mvn -pl !azure-samples package javadoc:aggregate -DskipTests=true || travis_terminate 1 ;
  else
   openssl aes-256-cbc -K $encrypted_25450b691aae_key -iv $encrypted_25450b691aae_iv -in my.azureauth.txt.enc -out my.azureauth.txt -d;
   export AZURE_TEST_MODE=RECORD || travis_terminate 1 ;
   export AZURE_AUTH_LOCATION=$TRAVIS_BUILD_DIR/my.azureauth.txt || travis_terminate 1 ;
   mvn -Dorg.slf4j.simpleLogger.defaultLogLevel=error || travis_terminate 1 ;
  fi



