spring:
  cloud:
    azure:
      client-id: [service-principal-id]
      client-secret: [service-principal-secret]
      tenant-id: [tenant-id]
      resource-group: [resource-group]
      
#     Uncomment below configurations if you want to enable auto creating resources.      
#      auto-create-resources: true
#      region: [region]
#      subscription-id: [subscription-id]
    stream:
      bindings:
        consume1-in-0:
          destination: [eventhub-1-name]
          group: [consumer-group]
        supply1-out-0:
          destination: [the-same-eventhub-1-name-as-above]
        consume2-in-0:
          binder: eventhub-2
          destination: [eventhub-1-name]
          group: [consumer-group]
        supply2-out-0:
          binder: eventhub-2
          destination: [the-same-eventhub-2-name-as-above]

      binders:
        eventhub-1:
          type: eventhub
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    namespace: [first-eventhub-namespace]
                    checkpoint-storage-account: [checkpoint-storage-account]
                    checkpoint-container: [checkpoint-container-1]
        eventhub-2:
          type: eventhub
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    namespace: [second-eventhub-namespace]
                    checkpoint-storage-account: [checkpoint-storage-account]
                    checkpoint-container: [checkpoint-container-2]
      eventhub:
        bindings:
          consume1-in-0:
            consumer:
              checkpoint-mode: MANUAL
          consume2-in-0:
            consumer:
              checkpoint-mode: MANUAL

      function:
        definition: consume1;supply1;consume2;supply2;
      poller:
        initial-delay: 0
        fixed-delay: 1000
