# If we configure the azure.activedirectory.client-id or azure.activedirectory.app-id-uri will be to check the audience.
# In v2.0 tokens, this is always the client ID of the API, while in v1.0 tokens it can be the client ID or the resource URI used in the request.
# If you are using v1.0 tokens, configure both to properly complete the audience validation.

#azure:
#  activedirectory:
#    client-id: <client-id>
#    app-id-uri: <app-id-uri>