server:
  port: 8081

azure:
  activedirectory:
    client-id: [resource-server-application-client-id]
    client-secret: [resource-server-application-client-secret]
    tenant-id: [teanant-id-registered-by-application]
    app-id-uri: [current-expose-application-id-url]
    authorization:
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read
      custom:
        scopes:
          - [custom-resource-server-expose-api-scope]