spring:
  cloud:
    azure:
      client-id: [service-principal-id]
      client-secret: [service-principal-secret]
      tenant-id: [tenant-id]
      resource-group: [resource-group]

#     Uncomment below configurations if you want to enable auto creating resources.
#
#      subscription-id: [ subscription-id ]
#      auto-create-resources: true
#      environment: Azure
#      region: [ region ]

      eventhub:
        namespace: [eventhub-namespace]
        checkpoint-storage-account: [checkpoint-storage-account]
        checkpoint-container: [checkpoint-container]
    stream:
      bindings:
        consume-in-0:
          destination: [eventhub-name]
          group: [consumer-group]
        supply-out-0:
          destination: [the-same-eventhub-name-as-above]

      eventhub:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      function:
        definition: consume;supply;
      poller:
        initial-delay: 0
        fixed-delay: 1000

