omitted_paths:
  - archive/*
  - profiles/*
  - loganalytics/data-plane/samples/*
  - sdk/*/azure-*/samples/*
  - sdk/*/azure-monitor-opentelemetry-exporter/*/samples/*
  - sdk/applicationinsights/microsoft-azure-applicationinsights-query/samples/*
  - sdk/spring/azure-spring-boot-samples/*
  - sdk/loganalytics/microsoft-azure-loganalytics/samples/*
  - "*/resource-manager/*"
  - "sdk/*/mgmt-*/*"
  - eng/*
  - common/smoke-tests/*
  - samples/*
language: java
root_check_enabled: True
required_readme_sections:
  - "Azure .+ (client|plugin|shared) library for Java"
  - ^Getting started$
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$
known_presence_issues:
  - ['core/build-tools', '#2847']
  - ['cosmosdb/data-plane/commons', '#2847']
  - ['cosmosdb/data-plane/commons-test-utils', '#2847']
  - ['cosmosdb/data-plane/direct-impl', '#2847']
  - ['cosmosdb/data-plane/gateway', '#2847']
  - ['cosmosdb/data-plane/sdk', '#2847']
  - ['mediaservices/data-plane', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-autosuggest', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-computervision', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-contentmoderator', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customimagesearch', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customsearch', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customvision-prediction', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customvision-training', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-entitysearch', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-faceapi', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-imagesearch', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-luis-authoring', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-luis-runtime', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-newssearch', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-qnamaker', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-spellcheck', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-textanalytics', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-videosearch', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-visualsearch', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-websearch', '#2847']
  - ['sdk/core/azure-core', '#2847']
  - ['sdk/core/azure-core-auth', '#2847']
  - ['sdk/core/azure-core-management', '#2847']
  - ['sdk/e2e', '#2847']
  - ['sdk/eventgrid/azure-messaging-eventgrid', '#2847']
  - ['sdk/eventhubs/microsoft-azure-eventhubs-extensions', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-core', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-cryptography', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-extensions', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-webkey', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-test', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-complete', '#2847']
  - ['sdk/mediaservices/microsoft-azure-media', '#2847']
  - ['sdk/servicebus/microsoft-azure-servicebus', '#2847']
  # Changelog List
  - ['sdk/applicationinsights/microsoft-azure-applicationinsights-query/CHANGELOG.md', '#2847']
  - ['sdk/authorization/microsoft-azure-authentication-msi-token-provider/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-autosuggest/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-computervision/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-contentmoderator/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customimagesearch/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customsearch/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customvision-prediction/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-customvision-training/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-entitysearch/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-faceapi/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-imagesearch/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-luis-authoring/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-luis-runtime/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-newssearch/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-qnamaker/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-spellcheck/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-textanalytics/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-videosearch/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-visualsearch/CHANGELOG.md', '#2847']
  - ['sdk/cognitiveservices/ms-azure-cs-websearch/CHANGELOG.md', '#2847']
  - ['sdk/core/azure-core/CHANGELOG.md', '#2847']
  - ['sdk/core/azure-core-amqp/CHANGELOG.md', '#2847']
  - ['sdk/core/azure-core-http-netty/CHANGELOG.md', '#2847']
  - ['sdk/core/azure-core-http-okhttp/CHANGELOG.md', '#2847']
  - ['sdk/core/azure-core-management/CHANGELOG.md', '#2847']
  - ['sdk/core/azure-core-test/CHANGELOG.md', '#2847']
  - ['sdk/cosmos/azure-cosmos-examples/CHANGELOG.md', '#2847']
  - ['sdk/cosmos/azure-cosmos-benchmark/CHANGELOG.md', '#2847']
  - ['sdk/cosmos/CHANGELOG.md', '#2847']
  - ['sdk/eventgrid/azure-messaging-eventgrid/CHANGELOG.md', '#2847']
  - ['sdk/eventgrid/microsoft-azure-eventgrid/CHANGELOG.md', '#2847']
  - ['sdk/eventhubs/microsoft-azure-eventhubs/CHANGELOG.md', '#2847']
  - ['sdk/eventhubs/microsoft-azure-eventhubs-eph/CHANGELOG.md', '#2847']
  - ['sdk/eventhubs/microsoft-azure-eventhubs-extensions/CHANGELOG.md', '#2847']
  - ['sdk/e2e/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-core/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-cryptography/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-extensions/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-webkey/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-test/CHANGELOG.md', '#2847']
  - ['sdk/loganalytics/microsoft-azure-loganalytics/CHANGELOG.md', '#2847']
  - ['sdk/mediaservices/microsoft-azure-media/CHANGELOG.md', '#2847']
  - ['sdk/servicebus/microsoft-azure-servicebus/CHANGELOG.md', '#2847']
  - ['sdk/storage/microsoft-azure-storage-blob/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-complete/CHANGELOG.md', '#2847']

known_content_issues:
  - ['README.md', '#3113']
  - ['sdk/anomalydetector/azure-ai-anomalydetector/swagger/README.md', '#3113']
  - ['sdk/applicationinsights/microsoft-azure-applicationinsights-query/README.md', '#3113']
  - ['sdk/authorization/microsoft-azure-authentication-msi-token-provider/README.md', '#3113']
  - ['sdk/batch/microsoft-azure-batch/README.md', '#3113']
  - ['sdk/boms/azure-sdk-bom/README.md', '#3113']
  - ['sdk/boms/azure-sdk-template-bom/README.md', '#3113']
  - ['sdk/core/README.md', '#3113']
  - ['sdk/core/azure-core-experimental/README.md', '#3113']
  - ['sdk/cognitiveservices/ms-azure-cs-textanalytics/README.md', '#3113']
  - ['sdk/communication/azure-communication-callingserver/swagger/README.md', '#3113']
  - ['sdk/communication/azure-communication-chat/swagger/README.md', '#3113']
  - ['sdk/communication/azure-communication-sms/swagger/README.md', '#3113']
  - ['sdk/communication/azure-communication-identity/swagger/README.md', '#3113']
  - ['sdk/communication/azure-communication-phonenumbers/swagger/README.md', '#3113']
  - ['sdk/confidentialledger/azure-security-confidentialledger/swagger/README.md', '#3113']
  - ['sdk/cosmos/changelog/README.md', '#3113']
  - ['sdk/cosmos/faq/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-benchmark/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-examples/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-encryption/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-1_2-12/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/catalog-api.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/configuration-reference.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/local-emulator.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/quick-start.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-1_2-12/dev/README.md', '#3113']
  - ['sdk/cosmos/README.md', '#3113']
  - ['sdk/deviceupdate/azure-iot-deviceupdate/swagger/README.md', '#3113']
  - ['sdk/e2e/README.md', '#3113']
  - ['sdk/eventgrid/azure-messaging-eventgrid/swagger/README.md', '#3113']
  - ['sdk/eventgrid/microsoft-azure-eventgrid/README.md', '#3113']
  - ['sdk/eventhubs/microsoft-azure-eventhubs-eph/README.md', '#3113']
  - ['sdk/eventhubs/README.md', '#3113']
  - ['sdk/agrifood/azure-verticals-agrifood-farming/swagger/README.md', '#3113']
  - ['sdk/formrecognizer/azure-ai-formrecognizer/swagger/README.md', '#3113']
  - ['sdk/metricsadvisor/azure-ai-metricsadvisor/swagger/README.md', '#3113']
  - ['sdk/keyvault/README.md', '#3113']
  - ['sdk/keyvault/azure-security-keyvault-administration/README.md', '#3113']
  - ['sdk/loganalytics/microsoft-azure-loganalytics/README.md', '#3113']
  - ['sdk/monitor/azure-monitor-opentelemetry-exporter/swagger/README.md', '#3113' ]
  - ['sdk/monitor/azure-monitor-query/swagger/README.md', '#3113' ]
  - ['sdk/parents/azure-client-sdk-parent/README.md', '#3113']
  - ['sdk/purview/azure-analytics-purview-account/swagger/README.md', '#3113']
  - ['sdk/purview/azure-analytics-purview-catalog/swagger/README.md', '#3113']
  - ['sdk/purview/azure-analytics-purview-scanning/swagger/README.md', '#3113']
  - ['sdk/search/azure-search-documents/swagger/README.md', '#3113']
  - ['sdk/search/azure-search-documents/src/test/README.md', '#3113']
  - ['sdk/search/open-api/readme.md', '#3113']
  - ['sdk/servicebus/azure-messaging-servicebus/swagger/README.md', '#3113']
  - ['sdk/servicebus/microsoft-azure-servicebus/README.md', '#3113']
  - ['sdk/storage/azure-storage-blob/swagger/README.md', '#3113']
  - ['sdk/storage/azure-storage-blob-nio/README.md', '#3113']
  - ['sdk/storage/azure-storage-common/README.md', '#3113']
  - ['sdk/storage/azure-storage-file/swagger/README.md', '#3113']
  - ['sdk/storage/azure-storage-file-datalake/swagger/README.md', '#3113']
  - ['sdk/storage/azure-storage-file-share/swagger/README.md','has other required sections']
  - ['sdk/storage/azure-storage-queue/swagger/README.md', '#3113']
  - ['sdk/storage/microsoft-azure-storage-blob/README.md', '#3113']
  - ['sdk/storage/microsoft-azure-storage-blob/swagger/README.md', '#3113']
  - ['sdk/storage/azure-storage-blob-nio/README.md', '#3113']
  - ['sdk/storage/azure-storage-internal-avro/README.md', '#3113']
  - ['sdk/storage/README.md', '#3113']
  - ['sdk/synapse/azure-analytics-synapse-accesscontrol/swagger/README.md', '#3113']
  - ['sdk/synapse/azure-analytics-synapse-artifacts/swagger/README.md', '#3113']
  - ['sdk/synapse/azure-analytics-synapse-spark/swagger/README.md', '#3113']
  - ['sdk/synapse/azure-analytics-synapse-managedprivateendpoints/swagger/README.md', '#3113']
  - ['sdk/synapse/azure-analytics-synapse-monitoring/swagger/README.md', '#3113']
  - ['sdk/tables/azure-data-tables/swagger/README.md', '#3113']
  - ['sdk/textanalytics/azure-ai-textanalytics/swagger/README.md', '#3113']
  - ['sdk/translation/azure-ai-documenttranslator/swagger/README.md', '#3113']
  - ['sdk/videoanalyzer/azure-media-videoanalyzer-edge/swagger/README.md', '#3113']
  - ['sdk/webpubsub/azure-messaging-webpubsub/swagger/README.md', '#3113']

package_indexing_exclusion_list:
  - azure-loganalytics-sample
  - azure-applicationinsights-query-sample
