omitted_paths:
  - archive/*
  - profiles/*
  - loganalytics/data-plane/samples/*
  - sdk/*/azure-*/samples/*
  - sdk/authorization/microsoft-azure-authentication-msi-token-provider/*
  - sdk/*/azure-monitor-opentelemetry-exporter/*/samples/*
  - sdk/*/azure-monitor-opentelemetry-autoconfigure/*/samples/*
  - sdk/boms/spring-cloud-azure-dependencies/*
  - sdk/spring/*
  - "sdk/spring/*/*"
  - sdk/spring-experimental/*
  - "sdk/spring-experimental/*/*"
  - sdk/vision/azure-ai-vision-imageanalysis/src/test/*
  - "*/resource-manager/*"
  - "sdk/*/mgmt-*/*"
  - "sdk/*/swagger/*"
  - "sdk/*/codegen/*"
  - sdk/*/*-stress/*
  - doc/*
  - eng/*
  - samples/*
language: java
root_check_enabled: True
required_readme_sections:
  - "Azure .+ (client|plugin|shared) library for Java"
  - ^Getting started$
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$
known_presence_issues:
  - ['sdk/mediaservices/microsoft-azure-media', '#2847']
  - ['sdk/servicebus/microsoft-azure-servicebus', '#2847']
  # Changelog List
  - ['sdk/authorization/microsoft-azure-authentication-msi-token-provider/CHANGELOG.md', '#2847']
  - ['sdk/cosmos/azure-cosmos-examples/CHANGELOG.md', '#2847']
  - ['sdk/cosmos/azure-cosmos-kafka-connect/CHANGELOG.md', '#2847']
  - ['sdk/cosmos/azure-cosmos-spark-account-data-resolver-sample/CHANGELOG.md', '#2847']
  - ['sdk/cosmos/CHANGELOG.md', '#2847']
  - ['sdk/eventgrid/azure-messaging-eventgrid/CHANGELOG.md', '#2847']
  - ['sdk/eventhubs/microsoft-azure-eventhubs/CHANGELOG.md', '#2847']
  - ['sdk/eventhubs/microsoft-azure-eventhubs-eph/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-core/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-cryptography/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-extensions/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-webkey/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-test/CHANGELOG.md', '#2847']
  - ['sdk/mediaservices/microsoft-azure-media/CHANGELOG.md', '#2847']
  - ['sdk/servicebus/microsoft-azure-servicebus/CHANGELOG.md', '#2847']
  - ['sdk/keyvault/microsoft-azure-keyvault-complete/CHANGELOG.md', '#2847']

known_content_issues:
  - ['README.md', '#3113']
  - ['sdk/authorization/microsoft-azure-authentication-msi-token-provider/README.md', '#3113']
  - ['sdk/batch/microsoft-azure-batch/README.md', '#3113']
  - ['sdk/boms/azure-sdk-bom/README.md', '#3113']
  - ['sdk/boms/azure-sdk-template-bom/README.md', '#3113']
  - ['sdk/core/README.md', '#3113']
  - ['sdk/clientcore/README.md', '#3113']
  - ['sdk/clientcore/core/README.md', '#3113']
  - ['sdk/clientcore/http-netty4/README.md', '#3113']
  - ['sdk/clientcore/http-okhttp3/README.md', '#3113']
  - ['sdk/clientcore/tools/annotation-processor/README.md', '#3113']
  - ['sdk/clientcore/optional-dependency-tests/README.md', '#3113']
  - ['sdk/clientcore/annotation-processor/README.md', '#3113']
  - ['sdk/clientcore/annotation-processor-test/README.md', '#3113']
  - ['sdk/core/azure-core-experimental/README.md', '#3113']
  - ['sdk/cosmos/faq/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-benchmark/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-examples/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-kafka-connect/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-encryption/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3_2-12/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-1_2-12/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-2_2-12/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-3_2-12/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-4_2-12/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-5_2-12/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3-5_2-13/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark-account-data-resolver-sample/README.md', '#3113']
  - ['sdk/cosmos/fabric-cosmos-spark-auth_3/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3_2-12/dev/README.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3_2-12/docs/catalog-api.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3_2-12/docs/local-emulator.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3_2-12/docs/quick-start.md', '#3113']
  - ['sdk/cosmos/azure-cosmos-spark_3_2-12/Samples/DatabricksLiveContainerMigration/README.md', '#3113']
  - ['sdk/cosmos/README.md', '#3113']
  - ['sdk/e2e/README.md', '#3113']
  - ['sdk/eventhubs/microsoft-azure-eventhubs-eph/README.md', '#3113']
  - ['sdk/eventhubs/README.md', '#3113']
  - ['sdk/keyvault/README.md', '#3113']
  - ['sdk/keyvault/azure-security-keyvault-administration/README.md', '#3113']
  - ['sdk/monitor/azure-monitor-spring-native/README.md', '#3113']
  - ['sdk/parents/azure-client-sdk-parent/README.md', '#3113']
  - ['sdk/parents/azure-client-sdk-parent-v2/README.md', '#3113']
  - ['sdk/parents/azure-code-customization-parent/README.md', '#3113']
  - ['sdk/parents/azure-perf-test-parent/README.md', '#3113']
  - ['sdk/parents/clientcore-parent/README.md', '#3113']
  - ['sdk/search/azure-search-documents/src/test/README.md', '#3113']
  - ['sdk/search/open-api/readme.md', '#3113']
  - ['sdk/search/README.md', '#3113']
  - ['sdk/servicebus/microsoft-azure-servicebus/README.md', '#3113']
  - ['sdk/storage/azure-storage-blob-nio/README.md', '#3113']
  - ['sdk/storage/azure-storage-common/README.md', '#3113']
  - ['sdk/storage/azure-storage-blob-nio/README.md', '#3113']
  - ['sdk/storage/azure-storage-internal-avro/README.md', '#3113']
  - ['sdk/storage/README.md', '#3113']
  - ['sdk/tools/azure-sdk-archetype/README.md', '#3113']
  - ['sdk/tools/azure-sdk-build-tool/README.md', '#3113']
  - ['sdk/appconfiguration/spring-cloud-azure-appconfiguration-config-web/README.md', '#3113']
  - ['sdk/appconfiguration/spring-cloud-azure-appconfiguration-config/README.md', '#3113']
  - ['sdk/appconfiguration/spring-cloud-azure-feature-management-web/README.md', '#3113']

package_indexing_exclusion_list:
  - azure-loganalytics-sample
  - azure-applicationinsights-query-sample
