spring:
  cloud:
    stream:
      bindings:
        consume1-in-0:
          destination: [servicebus-queue-1-name]
        supply1-out-0:
          destination: [servicebus-queue-1-name-same-as-above]
        consume2-in-0:
          binder: servicebus-2
          destination: [servicebus-queue-2-name]
        supply2-out-0:
          binder: servicebus-2
          destination: [servicebus-queue-2-name-same-as-above]

      binders:
        servicebus-1:
          type: servicebus-queue
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: [servicebus-namespace-1-connection-string]
        servicebus-2:
          type: servicebus-queue
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: [servicebus-namespace-2-connection-string]
      servicebus:
        queue:
          bindings:
            consume1-in-0:
              consumer:
                checkpoint-mode: MANUAL
            consume2-in-0:
              consumer:
                checkpoint-mode: MANUAL
      function:
        definition: consume1;supply1;consume2;supply2;
      poller:
        initial-delay: 0
        fixed-delay: 1000
