image: Visual Studio 2017

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"

install:
  - cmd: python -m pip install codecov
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"

build_script:
  - mvn clean install -B -V -DskipITs


